// Curated Exercise Catalog — maps real exercise images (JPG) from GesDepNet
// to clean names, descriptions, categories and role positions.
// Images are stored in public/exercises/ as 0000XXX*.jpg

const BASE = import.meta.env.BASE_URL + 'exercises/';

const CATALOG = [
  { id: 1, name: 'Rueda de pases con finalización', cat: 'tecnica', dur: 15, img: '0000001AXSXOK72AB.jpg', desc: 'Rueda de pases en movimiento con finalización a portería.', roles: ['A','B','B1','B2','B3','C'] },
  { id: 2, name: 'Cuadros y ruedas de pase', cat: 'tecnica', dur: 15, img: '0000002AYT2ERNPRB.jpg', desc: 'Sistema de pases en cuadrado con desplazamiento.' },
  { id: 3, name: 'Rueda de pases con finalización (2)', cat: 'tecnica', dur: 15, img: '0000003AUGG5A8SFB.jpg', desc: 'Variante de rueda de pases con remate.' },
  { id: 4, name: 'Acciones físico-técnicas 1', cat: 'fisico', dur: 15, img: '0000004AZNFPR2LCB.jpg', desc: 'Pase largo + eslalon + pared + salto vallas + remate.', roles: ['A','B'] },
  { id: 5, name: 'Acciones físico-técnicas 2', cat: 'fisico', dur: 15, img: '0000005AQ95IIDINB.jpg', desc: 'Resistencia con balón. Conducción a conos a mayor distancia.', roles: ['A','B'] },
  { id: 6, name: 'Técnica y habilidad', cat: 'tecnica', dur: 15, img: '0000006AIW8KQGILB.jpg', desc: 'Ejercicio de técnica individual con balón.' },
  { id: 7, name: 'Conducción 4', cat: 'tecnica', dur: 15, img: '0000007ANTLJ3FJ7B.jpg', desc: 'Conducción entre conos con 4 balones simultáneos.' },
  { id: 8, name: 'Conducción 5', cat: 'tecnica', dur: 15, img: '0000008ATAMCUP26B.jpg', desc: 'Conducción entre grupo de 2 conos, eslalon y sprint.' },
  { id: 9, name: 'Técnica y habilidad (2)', cat: 'tecnica', dur: 15, img: '0000009AM37WCGMKB.jpg', desc: 'Ejercicio analítico de técnica individual.' },
  { id: 10, name: 'Técnica y habilidad (3)', cat: 'tecnica', dur: 15, img: '0000010AD3JPBO4KB.jpg', desc: 'Trabajo de control orientado y pase.' },
  { id: 11, name: 'Técnica y habilidad (4)', cat: 'tecnica', dur: 15, img: '0000011ARWWOS8L8B.jpg', desc: 'Secuencia de pases con desplazamiento.' },
  { id: 12, name: 'Técnica y habilidad (5)', cat: 'tecnica', dur: 15, img: '0000012AD3QXFL1YB.jpg', desc: 'Control y pase en movimiento.' },
  { id: 13, name: 'Técnica y habilidad (6)', cat: 'tecnica', dur: 15, img: '0000013APVL8YAUJB.jpg', desc: 'Ejercicio de pases en triángulo.' },
  { id: 14, name: 'Técnica y habilidad (7)', cat: 'tecnica', dur: 15, img: '0000014AHHQYB2I6B.jpg', desc: 'Pases con cambio de dirección.' },
  { id: 15, name: 'Técnica y habilidad (8)', cat: 'tecnica', dur: 15, img: '0000015AC14J8FCWB.jpg', desc: 'Circuito de pases y desplazamientos.' },
  { id: 16, name: 'Pases y regates 1', cat: 'tecnica', dur: 15, img: '0000016ASAKULNZFB.jpg', desc: 'Acciones técnicas de pases combinados con regates.' },
  { id: 17, name: 'Cambios de orientación y tiro', cat: 'fisico', dur: 15, img: '0000017AQ98NY8HCB.jpg', desc: 'Físico-técnico: cambios de orientación, conducción y tiro.' },
  { id: 18, name: 'Acciones combinativas + finalización 7', cat: 'tactica', dur: 15, img: '0000018ADKXA2HVKB.jpg', desc: 'Combinaciones en equipo con finalización.' },
  { id: 19, name: 'Acciones combinativas + finalización 8', cat: 'tactica', dur: 15, img: '0000019ABYT1T09LB.jpg', desc: 'Jugada combinativa con remate a portería.' },
  { id: 20, name: 'Acciones combinativas + finalización 9', cat: 'tactica', dur: 15, img: '0000020AAEVBCOF3B.jpg', desc: 'Combinación con centro y remate.' },
  { id: 22, name: 'Rondo con desplazamiento 1', cat: 'tecnica', dur: 15, img: '0000022AS87WEHEYB.jpg', desc: 'Rondo con movimiento de jugadores entre posiciones.' },
  { id: 23, name: 'Rondo 1', cat: 'tecnica', dur: 15, img: '0000023ATNUIWUV5B.jpg', desc: 'Rondo clásico de posesión.' },
  { id: 24, name: 'Tiro tras regate 1', cat: 'tecnica', dur: 15, img: '0000024ACM2SG4HGB.jpg', desc: 'Regate a defensor y tiro a puerta.' },
  { id: 25, name: 'Circuito físico-técnico 1', cat: 'fisico', dur: 20, img: '0000025ABHBTJEM3B.jpg', desc: 'Circuito con escalera, vallas, conos y finalización.' },
  { id: 26, name: 'Acciones físico-técnicas 3', cat: 'fisico', dur: 15, img: '0000026AL5IJ8DO4B.jpg', desc: 'Trabajo combinado físico y técnico en estaciones.' },
  { id: 27, name: 'Rondo por equipos 1', cat: 'tecnica', dur: 15, img: '0000027AAQ8TTS51B.jpg', desc: 'Rondo con equipos rotando posiciones.' },
  { id: 28, name: 'Técnica - Juegos 1', cat: 'tecnica', dur: 15, img: '0000028AOLXFFE63B.jpg', desc: 'Juego lúdico con balón para mejorar habilidad.' },
  { id: 29, name: 'Tiro tras velocidad y regate', cat: 'fisico', dur: 15, img: '0000029ALFZ1I59QB.jpg', desc: 'Sprint + regate + tiro a portería.' },
  { id: 30, name: 'Estrategia falta 1', cat: 'tactica', dur: 15, img: '0000030AYN8NCQREB.jpg', desc: 'Movimiento de jugadores en falta directa.' },
  { id: 31, name: 'Estrategia falta 2', cat: 'tactica', dur: 15, img: '0000031AK4D0IMGDB.jpg', desc: 'Variante de falta con pared y tiro.' },
  { id: 32, name: 'Acciones físico-técnicas 4', cat: 'fisico', dur: 15, img: '0000032AMEWA1HPXB.jpg', desc: 'Ejercicio físico-técnico con estaciones.' },
  { id: 33, name: 'Pases y desplazamientos', cat: 'tecnica', dur: 15, img: '0000033AJUTTF80QB.jpg', desc: 'Secuencias de pases con movimiento posicional.' },
  { id: 34, name: 'Cuadros con desplazamiento', cat: 'fisico', dur: 15, img: '0000034AQHT8FOS7B.jpg', desc: 'Ejercicio en cuadro con desplazamientos cortos.' },
  { id: 35, name: 'Partido con objetivos 2', cat: 'tactica', dur: 20, img: '0000035ALK7W5F18B.jpg', desc: 'Partido reducido con normas específicas.' },
  { id: 36, name: 'Conducción y pase 3', cat: 'tecnica', dur: 15, img: '0000036ASQVZI8DRB.jpg', desc: 'Conducción entre conos y pase al compañero.' },
  { id: 37, name: 'Acciones combinativas + finalización 10', cat: 'tactica', dur: 15, img: '0000037AUGYO0BODB.jpg', desc: 'Combinación con cambio de orientación y remate.' },
  { id: 38, name: 'Pase 7', cat: 'tecnica', dur: 15, img: '0000038ADCJ6SHTQB.jpg', desc: 'Secuencia de pases a distintas distancias.' },
  { id: 39, name: 'Partido reducido 1', cat: 'tactica', dur: 25, img: '0000039AXIWXC35JB.jpg', desc: 'Partido en espacio reducido con normas.' },
  { id: 40, name: 'Partido reducido 1 (variante)', cat: 'tactica', dur: 25, img: '0000040AFBLD6MHWB.jpg', desc: 'Variante de partido reducido con objetivos.' },
  { id: 41, name: 'Trabajo físico variado 1', cat: 'fisico', dur: 20, img: '0000041AD695O7ANB.jpg', desc: 'Circuito de trabajo físico con varias estaciones.' },
  { id: 42, name: 'Acciones físico-técnicas 5', cat: 'fisico', dur: 15, img: '0000042AS9IFV7A5B.jpg', desc: 'Combinación de ejercicios físicos y técnicos.' },
  { id: 43, name: 'Acciones físico-técnicas 6', cat: 'fisico', dur: 15, img: '0000043AJRLJH2V1B.jpg', desc: 'Circuito físico con conducción.' },
  { id: 44, name: 'Rondo con desplazamiento 2', cat: 'tactica', dur: 15, img: '0000044APRSBYW97B.jpg', desc: 'Rondo con cambio de posiciones.' },
  { id: 45, name: 'Conducción, regate y tiro', cat: 'tecnica', dur: 15, img: '0000045AZQXI813UB.jpg', desc: 'Secuencia: conducción entre conos, regate y tiro.' },
  { id: 46, name: 'Juego de persecución 2', cat: 'calentamiento', dur: 10, img: '0000046AV1RRJSN9B.jpg', desc: 'Juego de persecución con balón en espacio acotado.' },
  { id: 47, name: 'Pase 8', cat: 'tecnica', dur: 15, img: '0000047AHDEYO7WPB.jpg', desc: 'Pases a un toque en formación.' },
  { id: 48, name: 'Circuito físico-técnico 2', cat: 'fisico', dur: 20, img: '0000048ADFSW46LHB.jpg', desc: 'Circuito con estaciones físico-técnicas.' },
  { id: 49, name: 'Acciones físico-técnicas 8', cat: 'fisico', dur: 15, img: '0000049ASCB3YY33B.jpg', desc: 'Trabajo físico con balón.' },
  { id: 50, name: 'Acciones combinativas + finalización 31', cat: 'tactica', dur: 15, img: '0000050AUXNNJASDB.jpg', desc: 'Combinación con varios jugadores y remate.' },
  { id: 51, name: 'Velocidad de reacción 1', cat: 'fisico', dur: 15, img: '0000051AJEJ49AM1B.jpg', desc: 'Sprint de reacción con estímulos variados.' },
  { id: 52, name: 'Conducción, pared y pase', cat: 'tecnica', dur: 15, img: '0000052ALM4532D2B.jpg', desc: 'Conducción + pared con compañero + pase final.' },
  { id: 53, name: 'Pared y pase 2', cat: 'tecnica', dur: 15, img: '0000053ARBDSM4TSB.jpg', desc: 'Doble pared y pase en profundidad.' },
  { id: 54, name: 'Pase 9', cat: 'tecnica', dur: 15, img: '0000054AQK7KPSLEB.jpg', desc: 'Ejercicio analítico de pase a distintas distancias.' },
  { id: 55, name: 'Acciones físico-técnicas 9', cat: 'fisico', dur: 15, img: '0000055AVEJUFWHGB.jpg', desc: 'Circuito combinado de fuerza y técnica.' },
  { id: 56, name: 'Pase y tiro', cat: 'tecnica', dur: 15, img: '0000056APDMBSL5QB.jpg', desc: 'Secuencia de pase + desmarque + tiro a puerta.' },
  { id: 57, name: 'Pase 10', cat: 'tecnica', dur: 15, img: '0000057AK3UL81G6B.jpg', desc: 'Pases largos y cortos en secuencia.' },
  { id: 59, name: 'Acciones combinativas + finalización', cat: 'tactica', dur: 15, img: '0000059AHNTUTJN3B.jpg', desc: 'Combinación con cambio de orientación y remate.', roles: ['A','B','C'] },
  { id: 60, name: 'Rondo con desplazamiento 3', cat: 'tactica', dur: 15, img: '0000060ANUKNQF27B.jpg', desc: 'Rondo con desplazamientos largos.' },
  { id: 61, name: 'Posesión con finalización', cat: 'tactica', dur: 15, img: '0000061AJQRCRRR8B.jpg', desc: 'Juego de posesión con objetivo de finalizar.' },
  { id: 62, name: 'Pase 11', cat: 'tecnica', dur: 15, img: '0000062AHYPVUX5KB.jpg', desc: 'Pases en formación con movilidad.' },
  { id: 63, name: 'Estrategia saque de banda', cat: 'tactica', dur: 10, img: '0000063AW879GS0HB.jpg', desc: 'Movimientos coordinados en saque de banda.' },
  { id: 64, name: 'Estrategia córner 1', cat: 'tactica', dur: 10, img: '0000064AE2VBQX6ZB.jpg', desc: 'Movimientos de ataque en córner.' },
  { id: 65, name: 'Pase 12', cat: 'tecnica', dur: 15, img: '0000065AQBKCUBXQB.jpg', desc: 'Pases a un toque con desplazamiento.' },
  { id: 66, name: 'Acciones físico-técnicas', cat: 'fisico', dur: 15, img: '0000066AK2K3RCZ6B.jpg', desc: 'Pase por alto, control, pared + eslalon entre conos.', roles: ['A','B','B2','C'] },
  { id: 68, name: 'Juego de calentamiento', cat: 'calentamiento', dur: 10, img: '0000068AHADPGER7B.jpg', desc: 'Persecución con balón en área acotada. 3 perseguidores con peto.' },
  { id: 69, name: 'Acciones combinativas + finalización 1', cat: 'tactica', dur: 15, img: '0000069ATAP0D6Q5B.jpg', desc: 'Pase a B, cambio orientación a C, profundidad a A1, centro para remate.', roles: ['A','B','B1','C','C1'] },
  { id: 70, name: 'Acciones combinativas + finalización 2', cat: 'tactica', dur: 15, img: '0000070AR2F3DH35B.jpg', desc: 'Pase por alto a B, eslalon, A salta vallas, centro y remate.', roles: ['A','B','B1'] },
  { id: 71, name: 'Pase 2', cat: 'tecnica', dur: 15, img: '0000071AMXZANK32B.jpg', desc: 'Grupos enfrentados: control orientado y devolución.' },
  { id: 72, name: 'Tiro 1', cat: 'tecnica', dur: 15, img: '0000072ANWLJTYAAB.jpg', desc: 'Sprint desde línea de meta + tiro con balón enviado por compañero.', roles: ['A','B'] },
  { id: 73, name: 'Conducción 1', cat: 'tecnica', dur: 15, img: '0000073AULL1XVFCB.jpg', desc: 'Grupos enfrentados, conducción con velocidad hasta el compañero.' },
  { id: 74, name: 'Ejercicio táctico', cat: 'tactica', dur: 15, img: '0000074AA6C2YSKQB.jpg', desc: 'Ejercicio táctico extraído del diagrama.' },
  { id: 75, name: 'Acciones combinativas + finalización 5', cat: 'tactica', dur: 15, img: '0000075AGDMJQERWB.jpg', desc: 'Pase largo a B, recorrer picas, recibir de B y finalizar.', roles: ['A','B'] },
  { id: 76, name: 'Conducción 4', cat: 'tecnica', dur: 15, img: '0000076APJO77MX5B.jpg', desc: '3 variantes sobre mismos conos: ir-volver, eslalon, sprint.' },
  { id: 77, name: 'Acciones físico-técnicas 2', cat: 'fisico', dur: 15, img: '0000077ATAO7F0VOB.jpg', desc: 'Resistencia con balón. Conducción progresiva.', roles: ['A','B'] },
  { id: 78, name: 'Acciones físico-técnicas 1', cat: 'fisico', dur: 15, img: '0000078AHWT2IZAHB.jpg', desc: 'Pase largo, eslalon, pared, salto vallas y tiro.', roles: ['A','B'] },
  { id: 79, name: 'Conducción 5', cat: 'tecnica', dur: 15, img: '0000079AGJYQQKTGB.jpg', desc: 'Conducción entre conos con 4 balones simultáneos.' },
  { id: 80, name: 'Conducción y pase 2', cat: 'tecnica', dur: 15, img: '0000080AN7TWLKBPB.jpg', desc: 'Pase largo a B, control y conducción entre conos.', roles: ['A','B'] },
  { id: 81, name: 'Conducción y regate 1', cat: 'tecnica', dur: 15, img: '0000081AKD9SE8GQB.jpg', desc: 'Recorrer conos y superar contrario en el centro del cuadrado.' },
  { id: 82, name: 'Conducción, pared y pase 1', cat: 'tecnica', dur: 15, img: '0000082AW60LUU8WB.jpg', desc: 'Eslalon entre conos + pared con compañero.' },
  { id: 83, name: 'Combinativas de pase y conducción', cat: 'tecnica', dur: 15, img: '0000083AFFC66KM0B.jpg', desc: 'Pase a un toque a distintas distancias + conducción entre conos.' },
  { id: 84, name: 'Acciones combinativas + finalización 29', cat: 'tactica', dur: 15, img: '0000084AHFN5E7KTB.jpg', desc: 'A conduce entre conos → B pase largo → C doble pared con D → tiro.', roles: ['A','B','C','D'] },
  { id: 85, name: 'Combinativa con finalización', cat: 'tactica', dur: 15, img: '0000085AEJNCTRJIB.jpg', desc: 'Doble entrega/devolución a 1 toque + remate a puerta.', roles: ['A','B'] },
  { id: 86, name: 'Acciones físico-técnicas 18', cat: 'fisico', dur: 15, img: '0000086AW5U5QIU9B.jpg', desc: 'Zig-zag entre conos + pase en largo por alto al compañero.' },
  { id: 87, name: 'Acciones físico-técnicas 19', cat: 'fisico', dur: 15, img: '0000087ALVEWC8XZB.jpg', desc: 'Pases con desplazamiento: tocar cono, rodear, saltar valla.' },
  { id: 88, name: 'Acciones físico-técnicas 20', cat: 'fisico', dur: 15, img: '0000088ALSHZHHHDB.jpg', desc: 'A pasa a B, conduce hasta B1, pasa a A1. Ida y vuelta.', roles: ['A','A1','B','B1'] },
  { id: 89, name: 'Centros y tiro 1', cat: 'tecnica', dur: 15, img: '0000089AT6LYE0WQB.jpg', desc: 'Grupo estático centra para remate de cabeza.' },
  { id: 90, name: 'Conducción 7', cat: 'tecnica', dur: 15, img: '0000090ATQZDDSP7B.jpg', desc: '5 conos en circuito, conducir siempre volviendo al centro.' },
  { id: 91, name: 'Conducción 8', cat: 'tecnica', dur: 15, img: '0000091AGVT01D8QB.jpg', desc: 'Triángulo: conducción entre conos, eslalon y sprint.' },
  { id: 92, name: 'Acciones físico-técnicas 20 (var)', cat: 'fisico', dur: 15, img: '0000092AB3NCSW77B.jpg', desc: 'Variante: pase A→B, conducción, pase a A1.', roles: ['A','A1','B','B1'] },
  { id: 93, name: 'Conducción 7 (var)', cat: 'tecnica', dur: 15, img: '0000093AKDGJ5WTBB.jpg', desc: 'Circuito de conducción con 5 conos.' },
  { id: 94, name: 'Conducción 9', cat: 'tecnica', dur: 15, img: '0000094AZYRLWT5NB.jpg', desc: 'Conducción técnica con cambios de dirección.' },
  { id: 95, name: 'Conducción y pared 1', cat: 'tecnica', dur: 15, img: '0000095ATC9G2UJEB.jpg', desc: 'Conducción + pared con compañero.' },
  { id: 96, name: 'Pases y desplazamientos 2', cat: 'tecnica', dur: 15, img: '0000096AXDTVJ257B.jpg', desc: 'Secuencia de pases con desplazamiento posicional.' },
  { id: 97, name: 'Partido con objetivos (rebumbio)', cat: 'tactica', dur: 20, img: '0000097AERPQON2TB.jpg', desc: 'Partido reducido con normas especiales de gol.' },
  { id: 98, name: 'Acciones combinativas + finalización 3', cat: 'tactica', dur: 15, img: '0000098ACOC5Z2AEB.jpg', desc: 'Combinación con varios jugadores y finalización.', roles: ['A','B','C'] },
  { id: 99, name: 'Acciones combinativas + finalización 4', cat: 'tactica', dur: 15, img: '0000099AY0MFY7TMB.jpg', desc: 'Combinación con centro y remate.', roles: ['A','B'] },
  { id: 100, name: 'Acciones combinativas + finalización 6', cat: 'tactica', dur: 15, img: '0000100AKZ196HKJB.jpg', desc: 'Jugada elaborada con varias paredes y remate.' },
  { id: 101, name: 'Acciones físico-técnicas 10', cat: 'fisico', dur: 15, img: '0000101AATINZ78UB.jpg', desc: 'Circuito físico-técnico con intensidad media.' },
  { id: 102, name: 'Acciones físico-técnicas 11', cat: 'fisico', dur: 15, img: '0000102AERIQS94TB.jpg', desc: 'Estaciones de trabajo físico con balón.' },
  { id: 103, name: 'Acciones físico-técnicas 12', cat: 'fisico', dur: 15, img: '0000103AID7MVLCDB.jpg', desc: 'Combinación de sprint, conducción y pase.' },
  { id: 104, name: 'Acciones físico-técnicas 13', cat: 'fisico', dur: 15, img: '0000104AH7NCUM3XB.jpg', desc: 'Circuito con vallas, escalera y finalización.' },
  { id: 105, name: 'Acciones físico-técnicas 14', cat: 'fisico', dur: 15, img: '0000105AD5U09NEFB.jpg', desc: 'Trabajo combinado de resistencia y pase.' },
  { id: 106, name: 'Acciones físico-técnicas 15', cat: 'fisico', dur: 15, img: '0000106AY2THFYFAB.jpg', desc: 'Sprint con cambio de dirección y pase.' },
  { id: 107, name: 'Acciones físico-técnicas 16', cat: 'fisico', dur: 15, img: '0000107AA1VEKDB8B.jpg', desc: 'Circuito completo con todas las estaciones.' },
];

// Add the image URL to each exercise
export const EXERCISE_CATALOG = CATALOG.map(ex => ({
  ...ex,
  image_url: BASE + ex.img,
}));

export const CATEGORIES = [
  { id: 'all', label: 'Todos', icon: '📋' },
  { id: 'tecnica', label: 'Técnica', icon: '⚽' },
  { id: 'fisico', label: 'Físico', icon: '💪' },
  { id: 'tactica', label: 'Táctico', icon: '🧠' },
  { id: 'calentamiento', label: 'Calent.', icon: '🔥' },
];
